server:
  port: 8080

default_server: '127.0.0.1:3100'

# tls:
#   cert_path: 'examples/certs/cert.pem'
#   key_path: 'examples/certs/key.pem'

auth:
  method:
    !jwt
      secret: "secret"
      algorithm: "HS256"
  prefix: "Test"

rate_limit:
  max_tokens: 50
  refill_rate: 10

cache:
  size: 100
  type:
    !redis
      url: redis://127.0.0.1

routes:
  /users:
    endpoints: ['127.0.0.1:3101', '127.0.0.1:3102']
    needs_auth: true

  /test:
    endpoints: ['127.0.0.1:3103', '127.0.0.1:3104']
    token_weight: 0
    http_version: HTTP2

  /test/best:
    endpoints: ['127.0.0.1:3105', '127.0.0.1:3106']
    token_weight: 25

  /_static:
    endpoints: ['127.0.0.1:3104']
    is_static: true
    max_connections: 5
    http_version: HTTP2
